#pragma once

// Только этот файл нужно подключать для использования API транспорта

#include "command.hpp"
#include "response.hpp"
#include "response/abstract_response.hpp"
#include "command/open.hpp"
#include "command/close.hpp"
#include "command/create_iscsi_target_command.hpp"
#include "command/add_disk_to_scst_command.hpp"
#include "command/remove_iscsi_target_command.hpp"
#include "command/remove_disk_from_scst_command.hpp"
#include "command/connect_device_to_iscsi_target_command.hpp"
#include "response/text.hpp"
#include "command/create_raid_command.hpp"
#include "command/destroy_raid_command.hpp"
#include "command/create_lvm_command.hpp"
#include "command/create_logical_volume_command.hpp"
#include "command/destroy_lvm_command.hpp"
#include "command/create_cached_disk_command.hpp"
#include "command/detach_cached_disk_command.hpp"
#include "command/delete_logical_volume_command.hpp"
#include "command/disable_iscsi_target_command.hpp"
#include "command/disconnect_device_to_iscsi_target_command.hpp"
#include "response/list_raid_response.hpp"
#include "response/list_scst_response.hpp"
#include "response/list_logical_volume_response.hpp"
#include "command/list/list_logical_volume_command.hpp"
#include "command/list/list_raid_command.hpp"
#include "command/list/list_scst_command.hpp"
#include "command/enable_iscsi_target_command.hpp"