.TH "cmake-build-debug/command_api.pb.cc" 3 "Пн 21 Авг 2017" "Ceph_analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/command_api.pb.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'command_api\&.pb\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <google/protobuf/stubs/common\&.h>\fP
.br
\fC#include <google/protobuf/stubs/port\&.h>\fP
.br
\fC#include <google/protobuf/stubs/once\&.h>\fP
.br
\fC#include <google/protobuf/io/coded_stream\&.h>\fP
.br
\fC#include <google/protobuf/wire_format_lite_inl\&.h>\fP
.br
\fC#include <google/protobuf/descriptor\&.h>\fP
.br
\fC#include <google/protobuf/generated_message_reflection\&.h>\fP
.br
\fC#include <google/protobuf/reflection_ops\&.h>\fP
.br
\fC#include <google/protobuf/wire_format\&.h>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBgorynych::StaticDescriptorInitializer_command_5fapi_2eproto\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBgorynych\fP"
.br
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBINTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION\fP"
.br
.ti -1c
.RI "#define \fBDO_\fP(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"
.br
.ti -1c
.RI "#define \fBDO_\fP(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"
.br
.ti -1c
.RI "#define \fBDO_\fP(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBgorynych::protobuf_AssignDesc_command_5fapi_2eproto\fP () GOOGLE_ATTRIBUTE_COLD"
.br
.ti -1c
.RI "void \fBgorynych::protobuf_ShutdownFile_command_5fapi_2eproto\fP ()"
.br
.ti -1c
.RI "void \fBgorynych::protobuf_InitDefaults_command_5fapi_2eproto_impl\fP ()"
.br
.ti -1c
.RI "\fBgorynych::GOOGLE_PROTOBUF_DECLARE_ONCE\fP (protobuf_InitDefaults_command_5fapi_2eproto_once_)"
.br
.ti -1c
.RI "void \fBgorynych::protobuf_InitDefaults_command_5fapi_2eproto\fP ()"
.br
.ti -1c
.RI "void \fBgorynych::protobuf_AddDesc_command_5fapi_2eproto_impl\fP ()"
.br
.ti -1c
.RI "\fBgorynych::GOOGLE_PROTOBUF_DECLARE_ONCE\fP (protobuf_AddDesc_command_5fapi_2eproto_once_)"
.br
.ti -1c
.RI "void \fBgorynych::protobuf_AddDesc_command_5fapi_2eproto\fP ()"
.br
.ti -1c
.RI "const ::google::protobuf::EnumDescriptor * \fBgorynych::Command_Command_Type_descriptor\fP ()"
.br
.ti -1c
.RI "bool \fBgorynych::Command_Command_Type_IsValid\fP (int value)"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "struct \fBgorynych::StaticDescriptorInitializer_command_5fapi_2eproto\fP \fBgorynych::static_descriptor_initializer_command_5fapi_2eproto_\fP"
.br
.ti -1c
.RI "::google::protobuf::internal::ExplicitlyConstructed< Command_BIND_DISK_TO_SCST_Arguments > \fBgorynych::Command_BIND_DISK_TO_SCST_Arguments_default_instance_\fP"
.br
.ti -1c
.RI "::google::protobuf::internal::ExplicitlyConstructed< Command > \fBgorynych::Command_default_instance_\fP"
.br
.ti -1c
.RI "::google::protobuf::internal::ExplicitlyConstructed< Response > \fBgorynych::Response_default_instance_\fP"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define DO_(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"

.SS "#define DO_(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"

.SS "#define DO_(EXPRESSION)   if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure"

.SS "#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Ceph_analyze из исходного текста\&.
